// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-6TsqiE-fnyNQT9Kb_U7ufG2QS3oCmUI',
    appId: '1:163039517556:web:fcbcf91ea4b883c4df6a21',
    messagingSenderId: '163039517556',
    projectId: 'fir-getx-app-ecaac',
    authDomain: 'fir-getx-app-ecaac.firebaseapp.com',
    storageBucket: 'fir-getx-app-ecaac.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmmc2zXn_f--SJKg8bz10S5HZB5mX1f9A',
    appId: '1:163039517556:android:8a6c8908d8c39bcddf6a21',
    messagingSenderId: '163039517556',
    projectId: 'fir-getx-app-ecaac',
    storageBucket: 'fir-getx-app-ecaac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwnkE6dXkTTRL6kBjDRPCyrziYtqiTJrM',
    appId: '1:163039517556:ios:cd59674681ec58a0df6a21',
    messagingSenderId: '163039517556',
    projectId: 'fir-getx-app-ecaac',
    storageBucket: 'fir-getx-app-ecaac.appspot.com',
    iosClientId: '163039517556-6f8vllbdd0aundoj90ol819sg69747lj.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwnkE6dXkTTRL6kBjDRPCyrziYtqiTJrM',
    appId: '1:163039517556:ios:cd59674681ec58a0df6a21',
    messagingSenderId: '163039517556',
    projectId: 'fir-getx-app-ecaac',
    storageBucket: 'fir-getx-app-ecaac.appspot.com',
    iosClientId: '163039517556-6f8vllbdd0aundoj90ol819sg69747lj.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
